// Generated by CoffeeScript 1.9.3
var SIMLAngularBrunch, fs, mkdirp, siml, sysPath, write;

fs = require('fs');

siml = require('siml');

sysPath = require('path');

mkdirp = require('mkdirp');

write = function(path, content, append) {
  var dir;
  if (append == null) {
    append = false;
  }
  if (content == null) {
    return;
  }
  dir = sysPath.dirname(sysPath.normalize(path));
  return mkdirp(dir, '0775', function(err) {
    if (err != null) {
      throw err;
    }
    if (append != null) {
      return fs.appendFile(path, content, function(err) {
        if (err != null) {
          throw err;
        }
      });
    } else {
      return fs.writeFile(path, content, function(err) {
        if (err != null) {
          throw err;
        }
      });
    }
  });
};

module.exports = SIMLAngularBrunch = (function() {
  SIMLAngularBrunch.prototype.brunchPlugin = true;

  SIMLAngularBrunch.prototype.type = 'template';

  SIMLAngularBrunch.prototype.extension = 'siml';

  function SIMLAngularBrunch(config) {
    var ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9;
    this.templates = [];
    this["public"] = config.paths["public"];
    this.outFile = (Object.keys(config.files.templates.joinTo))[0] || 'templates.js';
    this.rootDir = config.files.templates.joinTo[this.outFile];
    this.createRouter = !!((ref = config.plugins) != null ? (ref1 = ref.siml) != null ? ref1.createRouter : void 0 : void 0);
    this.routerOptions = (ref2 = config.plugins) != null ? (ref3 = ref2.siml) != null ? ref3.routerOptions : void 0 : void 0;
    this.templatePrefix = ((ref4 = config.plugins) != null ? (ref5 = ref4.siml) != null ? ref5.templatePrefix : void 0 : void 0) || '';
    this.templateModuleName = ((ref6 = config.plugins) != null ? (ref7 = ref6.siml) != null ? ref7.moduleName : void 0 : void 0) || 'templates';
    this.templatePathSeparator = ((ref8 = config.plugins) != null ? (ref9 = ref8.siml) != null ? ref9.templatePathSeparator : void 0 : void 0) || '/';
  }

  SIMLAngularBrunch.prototype.compile = function(data, path, callback) {
    var content, e, error, name, path_hunks;
    try {
      content = siml.angular.parse(data, {
        pretty: false
      });
      path = path.replace(this.rootDir, '');
      path_hunks = path.split(sysPath.sep);
      name = path_hunks.pop().slice(0, -this.extension.length - 1);
      path_hunks.push(name);
      path = sysPath.join.apply(this, path_hunks);
      return this.templates[path] = {
        name: name,
        content: content
      };
    } catch (_error) {
      e = _error;
      error = "Error: " + e.message;
      if (e.type) {
        error = e.type + error;
      }
      if (e.filename) {
        return error += " in '" + e.filename + ":" + e.line + ":" + e.column + "'";
      }
    } finally {
      callback(error, '');
    }
  };

  SIMLAngularBrunch.prototype.onCompile = function(generated_files) {
    var data, router_module, template_module;
    router_module = this.createRouter ? '\n' + this.getRouterModule(this.templates) || '' : '';
    template_module = this.getTemplateModule(this.templates);
    data = "\n\n/* siml-angular-brunch start */\n\n" + template_module + "\n" + router_module + "\n\n/* siml-angular-brunch end */\n";
    return write(this["public"] + sysPath.sep + this.outFile, data, true);
  };

  SIMLAngularBrunch.prototype.getTemplateModule = function(templates) {
    var content, escaped_content, prefix, template, template_path;
    content = [];
    prefix = this.templatePrefix === '' ? '' : "" + this.templatePrefix + this.templatePathSeparator;
    for (template_path in templates) {
      template = templates[template_path];
      template_path = prefix + template_path.replace(/\//g, this.templatePathSeparator);
      escaped_content = template.content.replace(/'/g, "\\'");
      escaped_content = template.content.replace(/\n/g, "\\n");
      content.push("$templateCache.put('" + template_path + "', '" + escaped_content + "');");
    }
    return "// siml-angular-brunch templates\nangular.module('" + this.templateModuleName + "', [])\n  .run(['$templateCache', function($templateCache) {\n    " + (content.join('\n    ')) + "\n  }])";
  };

  SIMLAngularBrunch.prototype.getRouterModule = function(templates) {
    var content, controller_name, route_name, snakeCaseToClassCase, template, template_path;
    content = [];
    snakeCaseToClassCase = function(string) {
      return string[0].toUpperCase() + string.slice(1).replace(/\-(.{1})/g, function(whole, matched) {
        return matched.toUpperCase();
      });
    };
    for (template_path in templates) {
      template = templates[template_path];
      if (!((this.routerOptions.onlyUse != null) && template_path.indexOf(this.routerOptions.onlyUse) === 0)) {
        continue;
      }
      route_name = template_path.slice(template_path.indexOf(sysPath.sep, 1));
      controller_name = snakeCaseToClassCase(template.name);
      content.push("$routeProvider.when('" + route_name + "', { controller: '" + controller_name + "', templateUrl: '" + template_path + "' });");
    }
    if (this.routerOptions.defaultRoute != null) {
      content.push("$routeProvider.otherwise({ redirectTo: '" + this.routerOptions.defaultRoute + "' });");
    }
    return "// siml-angular-brunch router\nangular.module('" + (this.routerOptions.moduleName || 'router') + "', [])\n  .config(['$routeProvider', function($routeProvider) {\n    " + (content.join('\n    ')) + "\n  }])";
  };

  return SIMLAngularBrunch;

})();
