// Generated by CoffeeScript 1.6.3
var SIMLAngularBrunch, fs, mkdirp, siml, sysPath, write;

fs = require('fs');

siml = require('siml');

sysPath = require('path');

mkdirp = require('mkdirp');

write = function(path, content, append) {
  var dir;
  if (append == null) {
    append = false;
  }
  if (content == null) {
    return;
  }
  dir = sysPath.dirname(sysPath.normalize(path));
  return mkdirp(dir, '0775', function(err) {
    if (err != null) {
      throw err;
    }
    if (append != null) {
      return fs.appendFile(path, content, function(err) {
        if (err != null) {
          throw err;
        }
      });
    } else {
      return fs.writeFile(path, content, function(err) {
        if (err != null) {
          throw err;
        }
      });
    }
  });
};

module.exports = SIMLAngularBrunch = (function() {
  SIMLAngularBrunch.prototype.brunchPlugin = true;

  SIMLAngularBrunch.prototype.type = 'template';

  SIMLAngularBrunch.prototype.extension = 'siml';

  function SIMLAngularBrunch(config) {
    var _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    this.templates = [];
    this["public"] = config.paths["public"];
    this.outFile = (Object.keys(config.files.templates.joinTo))[0] || 'templates.js';
    this.rootDir = config.files.templates.joinTo[this.outFile];
    this.createRouter = !!((_ref = config.plugins) != null ? (_ref1 = _ref.siml) != null ? _ref1.createRouter : void 0 : void 0);
    this.routerOptions = (_ref2 = config.plugins) != null ? (_ref3 = _ref2.siml) != null ? _ref3.routerOptions : void 0 : void 0;
    this.templateModuleName = ((_ref4 = config.plugins) != null ? (_ref5 = _ref4.siml) != null ? _ref5.moduleName : void 0 : void 0) || 'templates';
  }

  SIMLAngularBrunch.prototype.compile = function(data, path, callback) {
    var content, e, error, name, path_hunks;
    try {
      content = siml.angular.parse(data, {
        pretty: false
      });
      path = path.replace(this.rootDir, '');
      path_hunks = path.split(sysPath.sep);
      name = path_hunks.pop().slice(0, -this.extension.length - 1);
      path_hunks.push(name);
      return this.templates.push({
        name: name,
        content: content,
        path: sysPath.join.apply(this, path_hunks)
      });
    } catch (_error) {
      e = _error;
      error = "Error: " + e.message;
      if (e.type) {
        error = e.type + error;
      }
      if (e.filename) {
        return error += " in '" + e.filename + ":" + e.line + ":" + e.column + "'";
      }
    } finally {
      callback(error, '');
    }
  };

  SIMLAngularBrunch.prototype.onCompile = function(generated_files) {
    var data, router_module, template_module;
    router_module = this.createRouter ? '\n' + this.getRouterModule(this.templates) || '' : '';
    template_module = this.getTemplateModule(this.templates);
    data = "\n\n/* siml-angular-brunch start */\n\n" + template_module + "\n" + router_module + "\n\n/* siml-angular-brunch end */\n";
    return write(this["public"] + sysPath.sep + this.outFile, data, true);
  };

  SIMLAngularBrunch.prototype.getTemplateModule = function(templates) {
    var content, escaped_content, template, _i, _len;
    content = [];
    for (_i = 0, _len = templates.length; _i < _len; _i++) {
      template = templates[_i];
      escaped_content = template.content.replace(/'/g, "\\'");
      content.push("$templateCache.put('" + template.path + "', '" + escaped_content + "');");
    }
    return "// siml-angular-brunch templates\nangular.module('" + this.templateModuleName + "', [])\n  .run(['$templateCache', function($templateCache) {\n    " + (content.join('\n    ')) + "\n  }])";
  };

  SIMLAngularBrunch.prototype.getRouterModule = function(templates) {
    var content, controller_name, route_name, template, _i, _len;
    content = [];
    for (_i = 0, _len = templates.length; _i < _len; _i++) {
      template = templates[_i];
      if (!((this.routerOptions.onlyUse != null) && template.path.indexOf(this.routerOptions.onlyUse) === 0)) {
        continue;
      }
      route_name = template.path.slice(template.path.indexOf(sysPath.sep, 1));
      controller_name = template.name[0].toUpperCase() + template.name.slice(1);
      content.push("$routeProvider.when('" + route_name + "', { controller: '" + controller_name + "', templateUrl: '" + template.path + "' });");
    }
    if (this.routerOptions.defaultRoute != null) {
      content.push("$routeProvider.otherwise({ redirectTo: '" + this.routerOptions.defaultRoute + "' });");
    }
    return "// siml-angular-brunch router\nangular.module('" + (this.routerOptions.moduleName || 'router') + "', [])\n  .config(['$routeProvider', function($routeProvider) {\n    " + (content.join('\n    ')) + "\n  }])";
  };

  return SIMLAngularBrunch;

})();
